fragment bookFields on Book {
  title
  price
  publishDate
  author {
    firstName
    lastName
  }
  ratings {
    stars
    comment
  }
}

query findBooksWithFragment {
  books {
    ...bookFields
  }
}
